# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 626bbadabed7648cf10b2130e7c433262fa23f5b1fad8c549a3cc559c4c8cd50003b9cf21269477e1e27990a779f77b229645c37f777f1403d00404849be19df

test:
  secret_key_base: 9536e345fe2a8931950c5a8c43f9cb7e3db3f8e205d17de69e6a5c0312e88d27f01bdd799de23a640428e7c9907d63fbfac22e199d6ef144fe38285d68b077aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
